"""Constants stated explicitly in the NSR paper.

Keep this module limited to values that are actually stated in the paper.  Any
architecture or simulator value that the paper does not publish belongs in the
implementation-assumption section of the documentation, not here.
"""

PAPER_MAP_SIZE_M = 3.2
PAPER_VOXEL_SIZE_M = 0.05
PAPER_GRID_SIZE = 64
PAPER_ROLLOUT_STEPS = 12
PAPER_PRUNING_ALPHA = 0.5
PAPER_INITIAL_LEARNING_RATE = 0.01
PAPER_FINAL_LEARNING_RATE = 0.0001
PAPER_CAMERA_COUNT = 4
PAPER_CAMERA_TILT_DEGREES = 30.0
PAPER_TERRAINS = ("stairs", "boxes", "walls", "poles", "corridors")

# Reproduction bookkeeping, not a paper hyper-parameter. It identifies the
# local contract used by newly captured files and prevents old NPZ files from
# being mistaken for data generated by the current terrain/metadata code.
REPRODUCTION_CAPTURE_SCHEMA_VERSION = 1
REPRODUCTION_TERRAIN_PROFILE = "paper_ranges_v2_structured_primitives"

# Reproduction bookkeeping, not a paper hyper-parameter.  It identifies the
# local contract used by newly captured files and prevents old NPZ files from
# being mistaken for data generated by the current terrain/metadata code.
REPRODUCTION_CAPTURE_SCHEMA_VERSION = 1
REPRODUCTION_TERRAIN_PROFILE = "paper_ranges_v2_structured_primitives"

# These are engineering defaults used by this reproduction.  The paper does
# not publish channel widths or convolution kernel sizes, so they must never be
# reported as recovered paper hyper-parameters.
IMPLEMENTATION_CHANNELS = (4, 8, 12, 16)
IMPLEMENTATION_SPATIAL_STRIDE = (2, 2, 2, 1)
IMPLEMENTATION_GENERATIVE_KERNEL = (2, 2, 2, 1)
